@startuml diagram
package sesi8A {
    class Mahasiswa {
        - String nama
        - String nim
        - int usia

        + Mahasiswa(String nama, String nim, int usia)
        + String getNama()
        + void setNama(String nama)
        + String getNim()
        + void setNim(String nim)
        + int getUsia()
        + void setUsia(int usia)
        + void displayInfo()
    }
}
@enduml
